GameStore.WebUI/Controllers/CartController.cs
using System.Linq;
using System.Web.Mvc;
using GameStore.Domain.Entities;
using GameStore.Domain.Abstract;
using GameStore.WebUI.Models;

namespace GameStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IGameRepository repository;
        private IOrderProcessor orderProcessor;

        public CartController(IGameRepository repo, IOrderProcessor processor)
        {
            repository = repo;
            orderProcessor = processor;
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Извините, ваша корзина пуста!");
            }

            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }
        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToRouteResult AddToCart(Cart cart, int gameId, string returnUrl)
        {
            Game game = repository.Games
                .FirstOrDefault(g => g.GameId == gameId);

            if (game != null)
            {
                cart.AddItem(game, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int gameId, string returnUrl)
        {
            Game game = repository.Games
                .FirstOrDefault(g => g.GameId == gameId);

            if (game != null)
            {
                cart.RemoveLine(game);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }
    }
}

GameStore.WebUI/Controllers/NavController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using GameStore.Domain.Abstract;

namespace GameStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IGameRepository repository;

        public NavController(IGameRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu()
        {
            IEnumerable<string> categories = repository.Games
                .Select(game => game.Category)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(categories);
        }
    }
}

GameStore.WebUI/Views/Cart/Checkout.cshtml
@model GameStore.Domain.Entities.ShippingDetails

@{
    ViewBag.Title = "GameStore: форма заказа";
}

<h2>Оформить заказ сейчас</h2>
<p>Пожалуйста введи ваши контактные данные, и мы сразу отправим товар!</p>


@using (Html.BeginForm())
{
    @Html.ValidationSummary();
    <h3>Данные</h3>
    <div class="form-group">
        <label>Ваше имя:</label>
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    </div>

    <h3>Адрес доставки</h3>
    foreach (var property in ViewData.ModelMetadata.Properties)
    {
        if (property.PropertyName != "Name" && property.PropertyName != "GiftWrap")
        {
            <div class="form-group">
                <label>@(property.DisplayName ?? property.PropertyName)</label>
                @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
            </div>
        }
    }



    <h3>Опции</h3>
    <div class="checkbox">
        <label>
            @Html.EditorFor(x => x.GiftWrap)
            Использовать подарочную упаковку?
        </label>
    </div>

    <div class="text-center">
        <input class="btn btn-primary" type="submit" value="Обработать заказ" />
    </div>
}

GameStore.WebUI/Views/Cart/Completed.cshtml
@{
    ViewBag.Title = "Заказ обработан";
}

<h2>Спасибо!</h2>
<p>Спасибо за выбор нашего магазина. Заказ в кратчайшие сроки будет отправлен в службу доставки.</p>

GameStore.WebUI/Views/Cart/Index.cshtml
@model GameStore.WebUI.Models.CartIndexViewModel
@{
    ViewBag.Title = "GameStore: ваша корзина";
}

    <div class="row">
        <div class="col-2">
            <ul class="nav flex-column">
                <li class="nav-item">
                    @Html.Action("Menu", "Nav")
                </li>
            </ul>
        </div>
        <div class="col-8">
            <h2 class="text-center">Ваша корзина</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th>Кол-во</th>
                        <th>Игра</th>
                        <th class="text-right">Цена</th>
                        <th class="text-right">Общая цена</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var line in Model.Cart.Lines)
                    {
                    <tr>
                        <td class="text-center">@line.Quantity</td>
                        <td class="text-left">@line.Game.Name</td>
                        <td class="text-right">@line.Game.Price.ToString("# лей")</td>
                        <td class="text-right">
                            @((line.Quantity * line.Game.Price).ToString("# лей"))
                        </td>
                        <td>
                            @using (Html.BeginForm("RemoveFromCart", "Cart"))
                            {
                                @Html.Hidden("GameId", line.Game.GameId)
                                @Html.HiddenFor(x => x.ReturnUrl)
                                <input class="btn btn-sm btn-warning" type="submit" value="Удалить" />
                            }
                        </td>
                    </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="3" class="text-right">Итого:</td>
                        <td class="text-right">
                            @Model.Cart.ComputeTotalValue().ToString("# лей")
                        </td>
                    </tr>
                </tfoot>
            </table>

            <div class="text-center">
                <a class="btn btn-primary" href="@Model.ReturnUrl">Продолжить покупки</a>
                @Html.ActionLink("Оформить заказ", "Checkout", null, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>

GameStore.WebUI/Views/Cart/Summary.cshtml
@model GameStore.Domain.Entities.Cart

<div class="navbar-right">
    @Html.ActionLink("Заказать", "Index", "Cart",
    new { returnUrl = Request.Url.PathAndQuery },
    new { @class = "btn btn-default navbar-btn" })
</div>

<div class="navbar-text navbar-right">
    <b>Ваша корзина:</b>
    @Model.Lines.Sum(x => x.Quantity) игр,
    @Model.ComputeTotalValue().ToString("# лей")
</div>