GameStore.WebUI/Controllers/CartController.cs
using System.Linq;
using System.Web.Mvc;
using GameStore.Domain.Entities;
using GameStore.Domain.Abstract;
using GameStore.WebUI.Models;

namespace GameStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IGameRepository repository;
        private IOrderProcessor orderProcessor;

        public CartController(IGameRepository repo, IOrderProcessor processor)
        {
            repository = repo;
            orderProcessor = processor;
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Извините, ваша корзина пуста!");
            }

            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }
        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToRouteResult AddToCart(Cart cart, int gameId, string returnUrl)
        {
            Game game = repository.Games
                .FirstOrDefault(g => g.GameId == gameId);

            if (game != null)
            {
                cart.AddItem(game, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int gameId, string returnUrl)
        {
            Game game = repository.Games
                .FirstOrDefault(g => g.GameId == gameId);

            if (game != null)
            {
                cart.RemoveLine(game);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }
    }
}

GameStore.WebUI/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GameStore.Domain.Abstract;
using GameStore.Domain.Entities;
using GameStore.WebUI.Models;

namespace GameStore.WebUI.Controllers
{
    public class GameController : Controller
    {
        //количество товаров на одной странице
        private IGameRepository repository;
        public int pageSize = 4;

        public GameController(IGameRepository repo)
        {
            repository = repo;
        }

        public ViewResult List(string category, int page = 1)
        {
            GamesListViewModel model = new GamesListViewModel
            {
                Games = repository.Games
                    .Where(p => category == null || p.Category == category)
                    .OrderBy(game => game.GameId)
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null ?
                repository.Games.Count() :
                repository.Games.Where(game => game.Category == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }

        public FileContentResult GetImage(int gameId)
        {
            Game game = repository.Games
                .FirstOrDefault(g => g.GameId == gameId);

            if (game != null)
            {
                return File(game.ImageData, game.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}
 

GameStore.WebUI/Views/Shared/GameSummary.cshtml
@model GameStore.Domain.Entities.Game

    <div class="well">
        @if (Model.ImageData != null)
        {
            <div class="pull-left" style="margin-right: 10px">
                <img  width="75" height="75"
                     src="@Url.Action("GetImage", "Game",
                new { Model.GameId })" />
            </div>
        }

        <div class="well">
            <h3>
                <strong>@Model.Name</strong>
                <span class="pull-right label label-primary">@Model.Price.ToString("# лей")</span>
            </h3>
            @using (Html.BeginForm("AddToCart", "Cart"))
            {
                <div class="pull-right">
                    @Html.HiddenFor(x => x.GameId)
                    @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                    <input type="submit" class="btn btn-success" value="Добавить в корзину" />
                </div>
            }
            <span class="lead">@Model.Description</span>
        </div>
    </div>

GameStore.WebUI/Views/Shared/_AdminLayout.cshtml
@using System.Web.Optimization
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/bundles/bootstrap/css")
    @Styles.Render("~/bundles/ bootstrap-theme/css")
    @Styles.Render("~/bundles/ErrorStyles/css")

    @Scripts.Render("~/bundles/jquery/js")
    @Scripts.Render("~/bundles/bootstrap/js")
    @Scripts.Render("~/bundles/jquery.validate/js")
    @Scripts.Render("~/bundles/jquery.validate.unobtrusive/js")

    <title></title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

GameStore.WebUI/Views/Shared/_Footer.cshtml
<br>
<hr class="my-2">
<footer class="page-footer font-small mdb-color lighten-3 pt-4">

    <!-- Footer Links -->
    <div class="container text-center text-md-left">

        <!-- Grid row -->
        <div class="row">

            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 mr-auto my-md-4 my-0 mt-4 mb-1">

                <!-- Content -->
                <h5 class="font-weight-bold text-uppercase mb-4">Footer Content</h5>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur, eligendi!</p>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos excepturi itaque ratione
                    consequatur quis veritatis!
                </p>

            </div>
            <!-- Grid column -->

            <hr class="clearfix w-100 d-md-none">

            <!-- Grid column -->
            <div class="col-md-2 col-lg-2 mx-auto my-md-4 my-0 mt-4 mb-1">

                <!-- Links -->
                <h5 class="font-weight-bold text-uppercase mb-4">About</h5>

                <ul class="list-unstyled">
                    <li>
                        <p>
                            <a href="#!">ГЛАВНВЯ</a>
                        </p>
                    </li>
                    <li>
                        <p>
                            <a href="#!">О НАС</a>
                        </p>
                    </li>
                    <li>
                        <p>
                            <a href="#!">СЕРВИС</a>
                        </p>
                    </li>
                    <li>
                        <p>
                            <a href="#!">КОМАНДА</a>
                        </p>
                    </li>
                </ul>

            </div>
            <!-- Grid column -->

            <hr class="clearfix w-100 d-md-none">

            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 mx-auto my-md-4 my-0 mt-4 mb-1">

                <!-- Contact details -->
                <h5 class="font-weight-bold text-uppercase mb-4">Address</h5>

                <ul class="list-unstyled">
                    <li>
                        <p>
                            <i class="fas fa-home mr-3"></i> Республика Молдова, Кишинёв
                        </p>
                    </li>
                    <li>
                        <p>
                            <i class="fas fa-envelope mr-3"></i> info@example.com
                        </p>
                    </li>
                    <li>
                        <p>
                            <i class="fas fa-phone mr-3"></i> + 01 234 567 88
                        </p>
                    </li>
                    <li>
                        <p>
                            <i class="fas fa-print mr-3"></i> + 01 234 567 89
                        </p>
                    </li>
                </ul>

            </div>
            <!-- Grid column -->

            <hr class="clearfix w-100 d-md-none">
        </div>
        <!-- Grid row -->

    </div>
    <!-- Footer Links -->
</footer>
<!-- Footer -->

GameStore.WebUI/Views/Shared/_Header.cshtml
<nav class="navbar-expand-md navbar navbar navbar-dark bg-dark sticky-top">
    <div class="container-fluid">
        <a href="#" class="navbar-brad"><img src="~/Content/img/4.png" alt=""></a>
        <a href="#" class="navbar-brad"><img src="~/Content/img/icon1.png" alt=""></a>
        <a href="#" class="navbar-brad"><img src="~/Content/img/icon2.png" alt=""></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarResponsive">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    @Html.ActionLink("Главная", "Index", "Home")
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">Про нас</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">Контакты</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">Сервис</a>
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Магазин", "List", "Game")
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">Регистрация</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

GameStore.WebUI/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>eUse System | @ViewBag.Title</title>

    @Styles.Render("~/bundles/bootstrap/css")
    @Styles.Render("~/bundles/Global/css")
    @Styles.Render("~/bundles/Slaider/css")
    @Styles.Render("~/bundles/Block/css")
    @Styles.Render("~/bundles/ErrorStyles/css")

    @Scripts.Render("~/bundles/jquery/js")
    @Scripts.Render("~/bundles/bootstrap/js")
    @Scripts.Render("~/bundles/popper.min/js")
</head>
<body>

    @Html.Partial("_Header")

    @RenderBody()

    @Html.Partial("_Footer")


</body>
</html>